apiVersion: v1
kind: Service
metadata:
  name: my-cas-v1
  namespace: andy-test
  labels:
    app: my-cas-v1
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-cas-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cas-v1
  namespace: andy-test
  labels:
    app: my-cas-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cas-v1
  template:
    metadata:
      labels:
        app: my-cas-v1
    spec:
      containers:
      - name: my-cas-v1
        image: containersol/k8s-deployment-strategies
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v6.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
